### ISSUE TITLE
.Debs not extracting, or just extracting a debian-binary

### ISSUE THREAD

**Issue by Z2r-YT** [mass1ve-err0r/wpkg#1]
I'm extracting some .debs from BigBoss and HYI, and the ones from HYI are just not extracting, and the BigBoss ones are just extracting ``debian-binary`` files that just have plaintext data of ``2.0``

opening these in 7-Zip show proper files and structure, so I'm not sure what is going on, but it certainly isn't doing what it's _meant to_

some extra info, I am obtaining these deb files from the latest Win32 release of [CyDownload](https://github.com/borishonman/cydownload/releases)

more details:
Windows 11 22H2 22621 1702
Using normal ``cmd`` terminal
.deb location: ``C:\Users\Liam\Downloads\repo\debs``
example command: ``wpkg -x com.slugrail.ipainstaller_3.23.deb inst`` (attempting to extract the contents of ``com.slugrail.ipainstaller_3.23.deb`` into ``./inst/``

**Comment by mass1ve-err0r** [comment]
Hey, thanks for reporting an issue.

This goes without saying but next time do not reference any pirate repositories as your source, people tend to ignore and auto-close issues solely based on that.
Whether you're actually pirating or not is irrelevant, just keep that in mind.


About the actual issue:
wpkg is *most likely* working as intended, I'm not sure how BigBoss is packaging their debian archives but if their data payload isn't a simple TAR archive, wpkg refuses to extract it albeit being able to.
That's a choice I made when initially designing since I didn't expect anyone to compress further - Do feel free to fork & adjust as needed! :)

**Comment by Z2r-YT** [comment]
alright, thanks.
to be honest i completely forgot that that i was mentioning a pirate repo in the heat of the moment because of just pure frustration of many failed attempts. regardless, thank you so much, ill look into it, and probably just figure something with a linux VM if worst comes to worst.

appreciate the work, Liam

**Comment by Evil0ctal** [comment]
> alright, thanks. to be honest i completely forgot that that i was mentioning a pirate repo in the heat of the moment because of just pure frustration of many failed attempts. regardless, thank you so much, ill look into it, and probably just figure something with a linux VM if worst comes to worst.
> 
> appreciate the work, Liam

Hi, I implemented the dpkg functionality in Python and added a lot of new stuff. Here is the github repository link:

https://github.com/Evil0ctal/SimpleTweakEditor
